### PR TITLE
Updated Github Action and config.js to run test

### LINKED ISSUE #29: Update GH actions to run the tests
Update the current GH action to run the tests also. Do not remove the linting check also.

### LINKED ISSUE #30: Add Firebase credentials in Environment secrets
**Is your feature request related to a problem? Please describe.**
Failing of Tests due to invalid credentials

**Describe the solution you'd like**
Add firebase credentials in Environment secrets

### PR DESCRIPTION
**Pull request by AbhiKul10**
**Describe the Feature you Added**
- Updated config.js
- Added environment/repo secrets
- Updated Github Action

Fixes #29 #30

### CODE REVIEW

**Comment by AbhiKul10** [comment]
@Wathsara @shehand Please Add Repository Secrets. I have DMed you on gitter.

**Comment by Wathsara** [comment]
> 
> 
> @Wathsara @shehand Please Add Repository Secrets. I have DMed you on gitter.

Can we update the GitHub action on the same PR.

**Comment by shehand** [comment]
> > @Wathsara @shehand Please Add Repository Secrets. I have DMed you on gitter.
> 
> I have added the secret. can we update the GitHub action on the same PR?

agreed!

**Comment by AbhiKul10** [comment]
Sure!

**Comment by Wathsara** [comment]
@AbhiKul10 Reason for the action failure? Is it cause of an action secret issue?

**Comment by AbhiKul10** [comment]
@Wathsara facing the same error. One of my test cases failed due to an invalid API. Did you include the quotes too while adding the credentials

**Comment by AbhiKul10** [comment]
> @AbhiKul10 Reason for the action failure? Is it cause of an action secret issue?

yes!

**Comment by AbhiKul10** [comment]
Screenshot 2021-07-10 at 6 20 41 PM

No values received

**Comment by shehand** [comment]
> Screenshot 2021-07-10 at 6 20 41 PM
> 
> No values received

Values are not visible through the logs I guess. Only 1 test is failing. Tried with and without quotes in the secrets. Error log is same for both cases. Refer the logs and fix the problem.

**Comment by AbhiKul10** [comment]
@shehand  
https://stackoverflow.com/a/62143130/9236336 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ https://www.edwardthomson.com/blog/github_actions_11_secrets.html 
I found these stating that Public repository pull_request events triggered by forks do not have access to secrets.

**Comment by shehand** [comment]
> @shehand
> https://stackoverflow.com/a/62143130/9236336
> https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ https://www.edwardthomson.com/blog/github_actions_11_secrets.html
> I found these stating that Public repository pull_request events triggered by forks do not have access to secrets.
> What should I do in this case? Can we remove the test cases that uses secrets?

can you check whether we can use travis-ci?

**Comment by AbhiKul10** [comment]
@shehand @Wathsara Can you please set up the project on circleci and also add the credentials as Environment Variables.

**Comment by AbhiKul10** [comment]
> > @shehand
> > https://stackoverflow.com/a/62143130/9236336
> > https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ https://www.edwardthomson.com/blog/github_actions_11_secrets.html
> > I found these stating that Public repository pull_request events triggered by forks do not have access to secrets.
> > What should I do in this case? Can we remove the test cases that uses secrets?
> 
> can you check whether we can use travis-ci?

Screenshot 2021-07-11 at 11 20 41 PM

CircleCI is working on my branch!

**Comment by shehand** [comment]
> @shehand @Wathsara Can you please set up the project on circleci and also add the credentials as Environment Variables.

unfortunately we do not have the rights to create circle-ci projects. Can you put his requirement on the gitter chat mentioning one of our org admin? That would solve this problem otherwise we have to think in a different way.

**Comment by AbhiKul10** [comment]
> > @shehand @Wathsara Can you please set up the project on circleci and also add the credentials as Environment Variables.
> 
> unfortunately we do not have the rights to create circle-ci projects. Can you put his requirement on the gitter chat mentioning one of our org admin? That would solve this problem otherwise we have to think in a different way.

@shehand I have sent this message on Gitter, until then can we remove that particular failing test from this PR so that I can work on other things too, if not removed my every other PR will fail the checks and I won't be able to make any progress. For that particular test, we can open an issue, and I'll resolve that whenever the project is added to CircleCI. Let me know if this is fine.😇

**Comment by shehand** [comment]
> > > @shehand @Wathsara Can you please set up the project on circleci and also add the credentials as Environment Variables.
> > 
> > 
> > unfortunately we do not have the rights to create circle-ci projects. Can you put his requirement on the gitter chat mentioning one of our org admin? That would solve this problem otherwise we have to think in a different way.
> 
> @shehand I have sent this message on Gitter, until then can we remove that particular failing test from this PR so that I can work on other things too, if not removed my every other PR will fail the checks and I won't be able to make any progress. For that particular test, we can open an issue, and I'll resolve that whenever the project is added to CircleCI. Let me know if this is fine.😇

yeah, let's do it that way. update the PR with that changes

**Comment by AbhiKul10** [comment]
@shehand Done! ✅ Please Review

**Review by shehand — APPROVED** [review]

**Pull request merged**
