### PR TITLE
Added Test Cases

### LINKED ISSUE #21: Add test cases for the application
**Is your feature request related to a problem? Please describe.**
Currently, no test cases are present. 

**Describe the solution you'd like**
Adding test cases will increase the stability of the app.

### PR DESCRIPTION
**Pull request by AbhiKul10**
**Describe the Feature you Added**
Added Snapshot Testing 

**How will your Feature Help?**
- Adding test cases will increase the stability of the app.
- Makes the project Bug Free
- Improves the quality of the Project
- Enhances the Performance of the Project

Fixes #21

### CODE REVIEW

**Comment by AbhiKul10** [comment]
@shehand @Wathsara Can you please guide me with the problem? - https://gitter.im/scorelab/go-social

**Comment by AbhiKul10** [comment]
@shehand it's working when I am changing example.config.js to config.js and declaring all the credentials as Environment Repository Secrets. Should I follow this approach? If yes! then should I create a new Pull Request for the same or commit to this one?

**Comment by AbhiKul10** [comment]
> @shehand it's working when I am changing example.config.js to config.js and declaring all the credentials as Environment Repository Secrets. Should I follow this approach? If yes! then should I create a new Pull Request for the same or commit to this one?

@shehand Please let me know if I should follow the above approach?

**Review by shehand — APPROVED** [review]

**Comment by AbhiKul10** [comment]
@shehand I'll be adding more test cases

**Comment by shehand** [comment]
@AbhiKul10, have you tried with an empty config file(same config file but there are no keys there, only variables with empty strings assigned as values)?

**Comment by AbhiKul10** [comment]
> @AbhiKul10, have you tried with an empty config file(same config file but there are no keys there, only variables with empty strings assigned as values)?

Yes! I tried this also, but one of my test cases failed due to invalid credentials. When I declared the firebase credentials as an environment variable and stored the credentials as repository secrets, it worked for me.

**Review by Wathsara — APPROVED** [review]

**Comment by Wathsara** [comment]
Let's update the Github action to execute these tests.

**Comment by AbhiKul10** [comment]
> Let's update the Github action to execute these tests.

@Wathsara Okay! But one test if failing due to this error - 

Screenshot 2021-07-09 at 1 10 28 AM
 
I have tested doing this - https://github.com/scorelab/Ask-SCoRe/pull/28#issuecomment-876618384 and this resolved the error. Please let me know if I should follow this before updating the GH action.

**Comment by Wathsara** [comment]
> 
> 
> > Let's update the Github action to execute these tests.
> 
> @Wathsara Okay! But one test if failing due to this error -
> 
> Screenshot 2021-07-09 at 1 10 28 AM
> 
> I have tested doing this - [#28 (comment)](https://github.com/scorelab/Ask-SCoRe/pull/28#issuecomment-876618384) and this resolved the error. Please let me know if I should follow this before updating the GH action.

@AbhiKul10 If you need us to update the action secrets to pass the test case, please give us the secrets and we'll update them in action secrets.

**Review by shehand — APPROVED** [review]
As we have tests available now, let's update the GH action also.

**Pull request merged**
